### ISSUE TITLE
create issues landing page view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#109]
This will replace http://pulitzercenter.org/gateways and be linked to from the Reporting page.

**Comment by xaqrox** [comment]
Should be at `/issues`, per #274

**Comment by jselt** [comment]
any thoughts on display?

Grid? Image, title,teaser?

Some sort of intro box?

thoughts?

**Comment by jselt** [comment]
Well that matches what they have now - except for the post date - I'll add that and order by it with a sticky override.
