### ISSUE TITLE
improvements to Lesson Builder search

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#112]
adapt Lesson Builder resource search to behave more like planned Reporting landing page search (see #48)

**Comment by daniellerad** [comment]
also #141

**Comment by xaqrox** [comment]
From #141:
>The Lesson Builder should have the same search/filter functionality as the Reporting page, except for removing the irrelevant fields (Publication, Media) and replacing them with relevant fields (Level/Audience, Subject).

**Comment by xaqrox** [comment]
Wait. Is this the resource search, when you're adding resources to a lesson? Or the main community/model lessons search?

**Comment by daniellerad** [comment]
it's for searching lessons...but now youre making me second-guess

**Comment by xaqrox** [comment]
The comments above seem to suggest both possibilities

**Comment by daniellerad** [comment]
yes, it's for searching the community and model lessons. not for searching for resources to add to lessons.

**Comment by xaqrox** [comment]
bummer.

**Comment by daniellerad** [comment]
bummer why?
