### ISSUE TITLE
configure sitemap for SEO

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#113]

**Comment by jselt** [comment]
Here's an interesting question - do we include lessons in this, when we can't exclude based on draft status?

**Comment by jselt** [comment]
I mean I'm sure I can whip something up with some hooks - but it's out of scope since Lesson Builder doesn't bother to use, ya know, actual Drupal published status.

**Comment by daniellerad** [comment]
Ack. No, let's skip Lessons for now.
