### ISSUE TITLE
create user-facing sitemap

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#120]

**Comment by daniellerad** [comment]
Let's create a Sitemap page that shows the Primary Links menu and Secondary Links menu in some sort of nice list format. This Sitemap will need to be linked to from the Footer Util menu.

Is it possible to only show the "Enabled" items? If not, we'll want to wait on publishing this Sitemap until Jeff cleans up the Primary Links menu.

**Comment by xaqrox** [comment]
done in #363
