### ISSUE TITLE
"my lessons" in lesson builder only showing 10 most recent lessons

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#125]
When clicking on "My Lessons" in the builder, it only lists the 10 most recent lessons.  If a user has more than 10, the additional lessons don't display.  Since this is the only way users can edit lessons through the front end, the education team is concerned that our most prolific teachers won't be able to access their lessons. (It should dynamically load more on scroll.)

**Comment by xaqrox** [comment]
This should be done, but I don't know any live users that are experiencing this problem. Let's ask Jeff to test before closing?

**Comment by daniellerad** [comment]
pinged jeff - will circle back when he tests

**Comment by daniellerad** [comment]
jeff confirmed w/ the education team that it works. closing!
