### ISSUE TITLE
quote: additional lesson builder metadata work

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#129]
Now that we're over the biggest hurdle (Lesson Plan metadata is appearing on FB & Google), there are some improvements that Jeff wants to incorporate:
- Turn Twitter Cards on and validate/whitelist, as needed.
- Set the first image under the "Resources" sidebar as the og:image (umm, I kinda disagree with this).
- Set the"Summary" field (that is built into the Lesson Plans already -- it populates the description on the Community page, Model Lessons, etc.) as the meta:description field.

**Comment by daniellerad** [comment]
We have 4-6 hours budgeted for this work.

**Comment by xaqrox** [comment]
That should be enough, no prob.

**Comment by xaqrox** [comment]
> Set the"Summary" field (that is built into the Lesson Plans already -- it populates the description on the Community page, Model Lessons, etc.) as the meta:description field.

This is already the case, for `description` and `og:description`, which twitter will pick up.
