### ISSUE TITLE
create related lessons backreference view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#130]

**Comment by xaqrox** [comment]
Where does "see more lesson plans" go?

**Comment by daniellerad** [comment]
This should go to a page with the full list of Lesson Plans related to this story, if there are any. If there are not any related Lesson Plans, I guess just to the main Lesson Builder?

**Comment by xaqrox** [comment]
Is there such a page? Is that part of the lesson builder or a listing in the main site?

**Comment by daniellerad** [comment]
As of now, it pops up in a lightbox.

**Comment by xaqrox** [comment]
this is gonna link to a lesson builder ng view. somehow.
