### ISSUE TITLE
create related project view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#131]

**Comment by xaqrox** [comment]
where does "see more stories..." link?

**Comment by daniellerad** [comment]
Do you mean "See more stories in this project"?

This should go to the Project page (of which this story is a part). Stories will be on this page, on the default toggle/tab.

**Comment by xaqrox** [comment]
Moved to Project Node milestone to make sure I circle back and figure out how to link directly to the stories area. Presumably other content types are going to want to activate their corresponding tabs as well
