### ISSUE TITLE
make sure roadskillmap.org keeps working

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#139]
Need to update the [services view](http://pulitzer.dev/admin/structure/views/view/roads_kill/edit) that powers this app to look for Story nodes instead of nodes tagged "Reporting".

Also for peace of mind, deploy to dev.pulitzercenter.org at some point and change the GET request from roadskillmap.org to try the updated view. (@danielle to let client know)

**Comment by daniellerad** [comment]
https://radcampaign.basecamphq.com/projects/13453795-main-pulitzer-project/posts/100139076/comments 

Mentioned to client, and that's fine - we just needs to give them a heads up and coordinate a time whenever we're ready to do this. No rush.
