### ISSUE TITLE
create ebooks view (page lives under Reporting)

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#142]
Though you can filter Reporting by Media -> Ebooks, they also need an Ebooks landing page (http://pulitzercenter.org/reporting/ebooks). The current page is kind of a mess, and I'm wondering if we should just push them to link to the pre-filtered Reporting page?

**Comment by xaqrox** [comment]
Will be covered by work in [Term Page milestone](https://github.com/radcampaign/pulitzer2016/milestone/7)
