### ISSUE TITLE
make a plan for webforms

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#144]
Since we didn't do a form mockup, I want to make sure styling this doesn't slip through the cracks.

**Comment by jselt** [comment]
purple text on a pink background

**Comment by daniellerad** [comment]
💯

**Comment by daniellerad** [comment]
Hey Alex - webforms could use some front-end love so they match the style of the new site. I honestly haven't even looked at them. Maybe we can sit down together this afternoon and make a plan?

**Comment by AlexandraCasser** [comment]
@daniellerad  I think I can figure out how to make them more clearly match the comp--I specifically put them in favor of more dramatic changes while we were gearing up for deployment yesterday.  I'm happy to chat about it, though.  What time?

**Comment by daniellerad** [comment]
Standard styling is actually fine. The only thing we need to do is remove the "webform" label at the top of the page. Assigning @jselt

**Comment by daniellerad** [comment]
closing in faor of #222
