### ISSUE TITLE
update individual bio page

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#146]
We didn't mock this up, but there is a wireframe for this page.

Bio pages will display a photo and bio of a given staff member, grantee/reporter, intern, or student fellow. Rad will add a field (using the Media Library) to Users to allow Pulitzer Center admins to add an existing video that has already been added to the site (e.g. a Grantee’s Meet the Journalist interview) to bio pages. They will also show related Projects, Events, and E-Books.

**Comment by xaqrox** [comment]
basically duplicate of #106
