### ISSUE TITLE
Slider display

### ISSUE THREAD

**Issue by AlexandraCasser** [radcampaign/pulitzer2016#183]
@jselt , there's an extra sliver of a tile pushing the rest of the tiles to the right.  I think it needs to be fixed on the back end--could you get rid of it?

![pulitzer dev-](https://cloud.githubusercontent.com/assets/12383179/21854337/58a90276-d7e8-11e6-9f9c-9dc1358e2d1e.png)

**Comment by jselt** [comment]
I'll take a look

**Comment by AlexandraCasser** [comment]
Thanks 👍
