### ISSUE TITLE
event - image caption missing

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#191]
Not a huge rush, but something to be sure to fix.

You can see that captions on old events are still appearing, but the field on the backend to enter/edit is missing: http://pulitzercenter.org/event/gallery-opening-god-government-lgbt-rights-russia-india-uganda

**Comment by daniellerad** [comment]
From Jeff: 
"The captions have also disappeared from the Donate page back-end: http://pulitzercenter.org/donate We need this fixed ASAP, as the captions that are on the page are wrong, and we can't edit them."

**Comment by xaqrox** [comment]
This is fixed, live only, for events and pages. When I re-enabled it on events, the old content populated the Caption field, but the Donate page's captions seem to all be gone. I hope we didn't lose content...

**Comment by daniellerad** [comment]
Confirmed with Jeff that all is good. They did lose the content on the Donate page, but we're ok for now.

**Comment by xaqrox** [comment]
This needs to stay open because I need to get it into code and I will forget otherwise.
