### ISSUE TITLE
basic page QC

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#193]
This is looking so great! Noting everything I see, though I'm sure y'all are aware of most (if not all) of this. Let me know if you'd like me to split any of these into individual GH issues. Made a styling test page to work with: http://pccr.radcampaign.com/styling-test-page

Remove from public-facing view:

- [ ] Node label (Page) 
      -Needs to be handled on back end
- [ ] byline (by _____)
      -Needs to be handled on back end

Styling items:
- [x] H styles
- [x] blockquote should be Muli, border-left should be #002a4f, and it needs a 24px left margin to line up with indentation of lists
- [x] link styles need underline ("venenatis luctus" in 3rd paragraph is a link)

Back-end/content management:
- swap in better WYSIWYG
- scrap "Preview" button, replace with "Publish" button
- Image/Video/File Attachments Media Browser - "You are not authorized to access this page."
- how would i add a submenu?
- how would i add a sidebar?

**Comment by AlexandraCasser** [comment]
@daniellerad , should the byline be present on individual reporting pages?

**Comment by jselt** [comment]
Yes - don't hide either of those with CSS - they can be managed via backend code

**Comment by AlexandraCasser** [comment]
Thanks @jselt .  Do you know why the WYSIWYG is getting rid of H tags when you publish?

**Comment by jselt** [comment]
is it set to filtered html as the format type?

**Comment by AlexandraCasser** [comment]
@jselt It's set to filtered HTML, but when I set it to Full HTML the tags work.  Can we use full HTML or will that cause other problems?

**Comment by jselt** [comment]
No, go ahead and change it for styling.

**Comment by AlexandraCasser** [comment]
Thanks!

**Comment by daniellerad** [comment]
Closing this in favor of more specific issues (creating now).
