### ISSUE TITLE
homepage QC

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#194]
missing content:
- main hero needs date and publication above title
- need teaser blurb above stories, pulitzer center updates, education news
- need login button in footer (wait on sitemap for now)

- please make the featured images for each story/PC update/Ed news link to the individual node

styling:
- pulitzer center updates column needs light gray background (this also forces the content to be a bit narrower to allow for margin - the image spans the full width of the column, but all the text only spans about 90%)
- "see more stories"/"see more pulitzer center updates"/"see more education news" should all have a fixed position below the columns so they line up horizontally with each other; border and hover fill color should be #438496
- quote in footer should be italicized, and "Joseph Pulitzer III (1913-1993)" should be Muli uppercase

**Comment by jselt** [comment]
Not sure why the date and publication/category isn't showing for that item - it does locally for a different node - the one on staging may not have a pub date or other data possibly? I just added one at random.

I can't check right now cause the staging server has run out of HD space I need to move it - but other items are in #199 - pull request

**Comment by jselt** [comment]
The date and categories not showing up appear to only apply to newer nodes. 

Is it possible that none of the newer nodes have values in field_published_date? @xaqrox - Is that field supposed to be set automatically? It's currently not showing on the node form.

I set an older node (from Dec 12) to show in the main hero area - to see the issue just swap the order of items in the entity queue.

(and yeah I know the formatting of the publication is off @daniellerad :) - it's fixed in the pull request #199)

**Comment by xaqrox** [comment]
Yes, the publish date got problems. If you want to force it, the field is present on the node forms... just hidden with css
![iwkad22r](https://cloud.githubusercontent.com/assets/394919/22225794/e5fa69d2-e191-11e6-9950-8fe5348d4f15.jpg)

**Comment by xaqrox** [comment]
Anyway @daniellerad this is up on http://pccr.radcampaign.com, gimme a :+1: and I'll merge+close

**Comment by jselt** [comment]
Well - is there a solution in the works? Is it something they add now? If I force it, it doesn't seem like a long-term fix

**Comment by xaqrox** [comment]
Yes there is a solution in progress, it's waiting on the live site for confirmation. I reluctant to commit it just yet because I don't trust/understand it yet.

**Comment by xaqrox** [comment]
and we're putting it off in favor of being more prepared for the walkthru-they waited a week to let us know there was a problem so presumably it's something they can live with...?

**Comment by jselt** [comment]
k - it can wait I think - we can note it to them. I mainly wanted to make sure the view didn't have a problem.

**Comment by daniellerad** [comment]
All the QC items are beautifully resolved 💯

**Comment by AlexandraCasser** [comment]
@daniellerad Can we close this issue?

**Comment by daniellerad** [comment]
I think it gets closed when the pull request is done.
