### ISSUE TITLE
story QC

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#196]
- "reporting" in header should be active/underlined
- in sidebar, "authors" should just be "author"

**Comment by jselt** [comment]
what about if there are multiple authors. Do we care?

**Comment by daniellerad** [comment]
They approved "Author" in the comp, so that's what I'm going with.

**Comment by xaqrox** [comment]
...I feel like that's gonna come back to bite us...

**Comment by daniellerad** [comment]
It's possible but I can handle it at that point.

**Comment by daniellerad** [comment]
Closing!
