### ISSUE TITLE
education resource QC

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#197]
- content type should be "Education Resource" not "Educational Resource"
- "resources for teachers" in header should be active/underlined
- in sidebar, "authors" should just be "author"
- in related project box, it should say "This Education Resource is part of" instead of "This story is part of" - if that's time-consuming, let me know and we can tweak the wording to make it catch-all.
- media is missing: e.g. should be a video here: http://pccr.radcampaign.com/education/meet-journalist-ako-salemi

**Comment by jselt** [comment]
Yeah - the video is part of dealing with the  paragraphs - which I will do separately - #201

**Comment by daniellerad** [comment]
Closing this, with the exception of the media stuff which will be handled separately.
