### ISSUE TITLE
Project styles

### ISSUE THREAD

**Issue by jselt** [radcampaign/pulitzer2016#202]
Checkout the redesign branch
Pull
`drush en pc_block_class -y`
`drush fra -y`
`drush updb -y`
`drush cc all`

Go to a project page e.g. projects/iraq-battle-mosul

A lot of the styling is already there for elements it shares with other content types - but the header and tab areas need work

Comp is here: https://www.dropbox.com/s/yvkgq1qfuhvdg7l/pc-indivProject-final.psd?dl=0

Let @xaqrox know if you need any changes to backend stuff.

Thanks!

**Comment by AlexandraCasser** [comment]
@xaqrox Can I get a backend assist on the "Submitted by X on Y date" beneath the Project title?  Thanks in advance.

**Comment by jselt** [comment]
just pulled - looks great. closing
