### ISSUE TITLE
add author field to content admin page

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#203]
http://pulitzercenter.org/admin/content

So PC can search content by Author.

**Comment by xaqrox** [comment]
might be covered by #313, needs testing

**Comment by jselt** [comment]
Not seeing it - I can take this. I think the admin view (which is not user Admin_Views), could use some TLC aside from this too :)

**Comment by jselt** [comment]
*using

**Comment by xaqrox** [comment]
my comment was on the wrong issue *entirely*, shoulda been #118

**Comment by jselt** [comment]
hah - I was kind of wondering...
