### ISSUE TITLE
media missing from nodes

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#228]
Noting this so it doesn't get lost in the shuffle, though I know we're aware of this issue with the Media 2 module upgrade. None of the nodes that had media (photos, audio, slideshows, etc.) are appearing.

e.g. 
- should be a video here: http://pccr.radcampaign.com/education/meet-journalist-ako-salemi
- should be photo(s) here: http://pccr.radcampaign.com/reporting/residents-down-dumps-after-coal-slump

**Comment by jselt** [comment]
Just noting that this is all in #207 when the media module issue gets sorted

**Comment by jselt** [comment]
And I can fix all the merge conflicts then.

**Comment by xaqrox** [comment]
Definitely closed by #207, those links have the expected content now.
