### ISSUE TITLE
Buttons on Resources for Teachers page

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#233]
http://pccr.radcampaign.com/resources-for-teachers

Under the "Education Resources and News" section, the "See more education resources" and "See more education news" buttons should be centered in the section.

https://www.dropbox.com/s/uwtbksg71f6ty4i/pc-teacherResources-final.jpg?dl=0

**Comment by daniellerad** [comment]
Just noticed that they reported a similar styling tweak for mobile - can you make sure this fix also applies to mobile? (Right now, the buttons are bumping into each other.)

**Comment by jselt** [comment]
yerp
