### ISSUE TITLE
Header Nav style tweaks

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#234]
1) In header, the hover state of the menu items include a color change and a blue underline. Keep the color change, but remove the blue underline (it looks wonky because of the active state white underline).

2) Add a hover color change for search, sign up, and donate.

**Comment by jselt** [comment]
So not do what's in the comps?

**Comment by jselt** [comment]
Oh - I think some stuff got overwritten. Well I'll just do this.
