### ISSUE TITLE
Body link styles sitewide

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#235]
Hyperlinks are the same color as the body text unless you mouse over.

e.g. There are links in the body on this node: http://pccr.radcampaign.com/blog/pulitzer-center-launches-end-aids

Please match the link styles seen in the comps: https://www.dropbox.com/s/6180q2rfw3mxxtw/pc-basicPage-final.jpg?dl=0

Link should always be underlined, and should then change color (and keep underline) on hover.

**Comment by jselt** [comment]
Oh yeah - I meant to check on this one but, well, spaced

So which one is hover? I have no idea from that comp

**Comment by daniellerad** [comment]
I think link should always be underlined, and should then change color (and keep underline) on hover.

**Comment by jselt** [comment]
yeah but which is the default color before you hover - the dark blue (which is the same as the body text, or the light blue?

**Comment by daniellerad** [comment]
I think dark blue for general link state, then light blue on hover.

**Comment by jselt** [comment]
really? Ok

**Comment by daniellerad** [comment]
Does that not make sense? I'm open to whatever makes sense :)

**Comment by daniellerad** [comment]
I think that this may have messed up the link styles on landing pages like Reporting and Resources for Teachers and PC Updates (see underlines on story titles and publications and tabs). Reopening

**Comment by jselt** [comment]
Closing in favor of a new issue
