### ISSUE TITLE
add in box/block/bean whatever content

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#240]
Jeff provided the content for the various teaser text around the site, whenever we're ready for that.

**Comment by jselt** [comment]
they're just boxes - mouse over and the gear should appear. We can capture into features

**Comment by daniellerad** [comment]
Awesome will do when I have time (maybe tomorrow).

**Comment by jselt** [comment]
yeah just make sure we know that you've done it

**Comment by daniellerad** [comment]
Deal!

**Comment by daniellerad** [comment]
Did some, but keeping this issue open as a reminder to finish the others once the appropriate pages are deployed.
