### ISSUE TITLE
Issue node wonkiness

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#242]
Found some odd things going on, just tracking for the future

### missing splash
http://pulitzer.dev/learning-around-world
http://pulitzer.dev/waiting-for-water
http://pulitzer.dev/reproductive-health
http://pulitzer.dev/hivaids-caribbean

### funky content
http://pulitzer.dev/land-rights
http://pulitzer.dev/haiti-after-quake
http://pulitzer.dev/downstream

**Comment by jselt** [comment]
I did add a background color to branch I'm working on (related lessons and events for issues). 

Deffo some have some weird content bits.

**Comment by daniellerad** [comment]
I can deal with the content bits with the client.
