### ISSUE TITLE
Reporting - teaser for Projects should pull Summary field

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#243]
NOT the first few sentences of the body.

**Comment by jselt** [comment]
wait - they have a separate summary field instead of the one with the body?

&^*%*&^$(*(^*&%*&$*

**Comment by daniellerad** [comment]
.....yes.

**Comment by jselt** [comment]
Please kill me

**Comment by daniellerad** [comment]
I refuse!

**Comment by daniellerad** [comment]
Compiled list of changes requested for Reporting:

- [ ] Teaser should pull Summary field, not first bit of body

- [ ] Please add Contributor (Author) names and Project date, similar to how it appears on Story grid

**Comment by daniellerad** [comment]
Noting that this change should take place on all Project views, including on taxonomy term pages, e.g. http://pccr.radcampaign.com/region/asia

**Comment by jselt** [comment]
Is this only on this view or everywhere? Easier if it's everywhere :)

**Comment by daniellerad** [comment]
Everywhere 🎵 💃
