### ISSUE TITLE
Restyle reporting + projects exposed filters

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#246]
Because post date and Chosen.
![image](https://cloud.githubusercontent.com/assets/394919/22489378/32e2f760-e7e5-11e6-895e-b8e905c826eb.png)

(Assigning to @daniellerad cuz I don't know who has the bandwidth)

**Comment by jselt** [comment]
I'll take it.

ALL EXPOSED FORMS SHALL BE AS ONE

**Comment by jselt** [comment]
Hey @AlexandraCasser - do you want to take this - the elements replaced by Chosen (the selects) are going to be all over, so you can be pretty general with selectors for styles - placement may require more specificity form to form.

**Comment by jselt** [comment]
Attached is the look to aim for
![select](https://cloud.githubusercontent.com/assets/1815689/22514424/3f405cf4-e86d-11e6-89b2-12679f54406f.jpg)

**Comment by AlexandraCasser** [comment]
Yes!  [I was getting bored.](https://s-media-cache-ak0.pinimg.com/originals/a0/58/8f/a0588f1c0bf0617fb812fe34913aeeab.gif)

**Comment by AlexandraCasser** [comment]
@jselt what causes the different styles on these two dropdowns?  Pure CSS or Drupal magic?

![jmftg](https://cloud.githubusercontent.com/assets/12383179/22551707/db332fb8-e923-11e6-87e9-3db0e2e7a39c.png)
![ye55a](https://cloud.githubusercontent.com/assets/12383179/22551708/db336c9e-e923-11e6-8be8-1ff16cb4e564.png)

**Comment by jselt** [comment]
it's the settings for Chosen

/admin/config/user-interface/chosen

Just set the minimum number to something lower.
