### ISSUE TITLE
issue bar on homepage needs mobile styling

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#247]
The mobile styling for the issue bar was good (and just needed a little love for tablet) but now it's all wonky. Want to make sure it doesn't slip through the cracks.

**Comment by jselt** [comment]
Yeah - I think I forgot to add some config to a feature.

**Comment by AlexandraCasser** [comment]
Is this something that requires backend know-how or can I grab it?

**Comment by jselt** [comment]
it's just adding some config back in - thanks tho!
