### ISSUE TITLE
page title module config

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#249]
http://pulitzercenter.org/admin/config/search/page-title

The PC site currently has a module that allows for configuring a custom page <title> - see the current configuration on the live site in the link above.

This displays a field in the housekeeping tabs at the bottom of the node edit form, which is currently missing on the staging site. Please make sure the content from the live site is maintained, since they've entered lots of custom titles over the years.

**Comment by jselt** [comment]
I think they are just referring to the new types - it is displayed on others as before.

I'm adding it to those 3 and capturing in pc_admin feature - the data is there (same NIDs).

We typically don't use this module as it tends to get used to shorten page head titles which is actually not desirable from an SEO standpoint. Dunno if it's worth mentioning - the few I spot-checked looked pretty worthless in SEO terms (no improvement on the actual node title).

**Comment by daniellerad** [comment]
Ok cool - that works. Will definitely mention. Thank you!
