### ISSUE TITLE
create email signup box

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#25]
[FR](https://docs.google.com/document/d/1LMVo94yb8ibPW1sUJK5pB36BMX-zuMgy53vbAOAAyH4/edit#):

> We plan to improve the prominence of the email subscription call-out, and minimize the number of clicks for users as much as possible given any third-party system constraints.

**Comment by xaqrox** [comment]
@daniellerad do we have info about what CRM they are using/if there is an API or anything available?

**Comment by daniellerad** [comment]
MailChimp. Let me know when you're ready for login credentials.

**Comment by xaqrox** [comment]
:arrow_up: I'm ready. I assume we're working towards the usual dropdown email passthru form kinda thing?

**Comment by daniellerad** [comment]
Ok, MailChimp login has been updated in LastPass. If you log in to radcampaign in MailChimp, you'll see the access to Pulitzer :)

**Comment by xaqrox** [comment]
like http://polarisproject.org/

**Comment by xaqrox** [comment]
@daniellerad are you sure the mailchimp creds made it into the shared folder? i don't see them

**Comment by daniellerad** [comment]
Yep, they gave access to the general Rad login (I think it's in Allyson's name?).

**Comment by xaqrox** [comment]
@daniellerad do we know explicitly which list they want to be subscribing people to? I'm assuming "Combined Contacts 8/13/14" which has 9,791 subscribers, but want to make sure

**Comment by daniellerad** [comment]
Please use “Newsletter Subscribers” as the main list.
