### ISSUE TITLE
reporting filters should be collapsed with "advanced search"

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#252]
This is not crucial, but is a fix for the Reporting page. Only "keyword" should show unless you click "Advanced" to see more filters.

https://www.dropbox.com/s/6rq9o0oimarky9w/pc-reporting-r7-v1.jpg?dl=0

**Comment by xaqrox** [comment]
BEF is already enabled to put datepicker on post date filter, just need to enable/configure "secondary options"

**Comment by jselt** [comment]
@daniellerad - assuming this is true of event and pc update filters as well?

**Comment by daniellerad** [comment]
Hmm. We didn't discuss other pages specifically. If it's a quick change, then that's fine. Otherwise, we aren't tied to doing it.

**Comment by jselt** [comment]
well it triggers a need for restyling and it needs some form alters (but it's pretty much the same for all forms)

There is a "show less" link on the events comp - so I guess it's implied.

**Comment by jselt** [comment]
I just noticed the "show less" btw

**Comment by daniellerad** [comment]
Ok, thanks for checking.
