### ISSUE TITLE
active underline under donate in header

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#254]
It's a little smooshed. Maybe don't have the border extend under the icon? Or give it a bit of breathing room at the bottom? Not sure what's possible so as not to mess up the other active underline styles that are so perfect :)

![screen shot 2017-02-02 at 10 18 41 am](https://cloud.githubusercontent.com/assets/15112895/22555331/5f3f40d2-e931-11e6-9be7-b4f561c8a6de.png)

**Comment by jselt** [comment]
Not have the underline is basically it

**Comment by jselt** [comment]
maybe just make it white - does this actually go to an internal page????

**Comment by daniellerad** [comment]
I like that idea. Yerp, it goes to a landing page on their site.

**Comment by jselt** [comment]
Sigh

**Comment by jselt** [comment]
I'l just stick it in the branch I'm on
