### ISSUE TITLE
create main nav menu block

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#26]

**Comment by xaqrox** [comment]
Instead of creating a menu_block i thought we might take advantage of bootstrap's existing top-level nav markup. Sound good @jselt?

**Comment by jselt** [comment]
Is the main menu a dropdown? If so it's a little problematic as it then disables links on items with children. Which can be problematic.

If not then yep go for it.

**Comment by xaqrox** [comment]
I don't think we're planning on having dropdowns. But the real question is if the markup is going to work in the context of the other header elements. Looking at the [comps](https://www.dropbox.com/home/RAD/ClientWork/pulitzer%20center%20on%20crisis%20reporting/6\)%20design/Interiors/Round%202?preview=pc-basicPage-r7-v1.jpg) I assume the ideal order of the elements would be:
```
.logo*
.name*
#block-pc-block-social-buttons*
ul.nav.secondary*
ul.nav*
#block-search-form*
#block-pc-block-email-signup*
```
 Here is some jade markup representing the structure as is (*# indicates one of those elements mentioned above and their ideal order...)
```jade
header#navbar
  .container
    .navbar-header
      .logo*1
      .name*2
    .navbar-collapse
      nav
        ul.nav*5
        ul.nav.secondary*4
        .region-navigation
          #block-pc-block-social-buttons*3
          #block-search-form*6
          #block-pc-block-email-signup*7
```
That's pretty much as good as it gets using Bootstrap's default markup and Context to place the blocks. Other options include:

1. I could move the `ul.nav`s in to `.region-navigation`, before or after the blocks are printed. Probably will require the most tortured CSS.
2. I could pre-render in the blocks `hook_preprocess_region` or `_page` and print them explicitly in the template. Hard-code-y.
3. Menu blocks, no bootstrap markup. Drupal-y, divitis, menu_block export is a hassle.

:thinking:

**Comment by xaqrox** [comment]
Actually, thinking about #25 and #24, if those are gonna work the same way as Polaris (per @daniellerad's suggestion), then it doesn't matter where the blocks are because they are going to be absolute-positioned, and we can just build the trigger elements into the template... sound good?

**Comment by jselt** [comment]
I don't understand how this resembles polaris, but I can deal with the markup and placement

**Comment by xaqrox** [comment]
Polaris has a box that just has markup with trigger elements for email, search, and menu. and then there's js that manages the showing/hiding of the respective elements. I'll set it up.

**Comment by jselt** [comment]
ah - but there is no trigger for the menu needed  - or am I missing something?

**Comment by xaqrox** [comment]
no you're right i only mention it for completeness' sake in talking about he polaris implementation. it'lll just be email and search in this case.

**Comment by jselt** [comment]
k - cool.
