### ISSUE TITLE
lesson plans bugs & things to look into

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#262]
I have grouped the bugs that the PC team submitted that have to do with Lesson Plans getting pulled onto the main site. I would say that these are probably pretty important for them. Let's review today in the dev check-in.

- [x] http://pccr.radcampaign.com/education/lesson-plans - what is this page? should it exist or just push people to LB?

- [x] Lesson Plans missing from Projects: http://pccr.radcampaign.com/projects/1000-days-women-children-maternal-health-nutrition-world-developing-thurow - http://pulitzercenter.org/builder/lesson/16170 should be related lesson plan (missing from sidebar) and educational resource (missing from tabs)

- [x] Lesson Plans missing from Stories: http://pccr.radcampaign.com/reporting/widows-life-after-loss - http://pccr.radcampaign.com/builder/lesson/20653 should be related lesson plan (missing from sidebar)

- [x] Lesson Plans missing from Education resources: http://pccr.radcampaign.com/education/meet-the-journalist-richard-bernstein-taiwan - http://pulitzercenter.org/builder/lesson/19855 should be related lesson plan (missing from sidebar)

- [ ] On Projects, under Related Lesson Plans, "See More Lesson Plans" links to a page that is pulling non-relevant content (e.g. http://pccr.radcampaign.com/projects/suggestible-you links to http://pccr.radcampaign.com/builder/model-lessons/using/17972 but this list should match "See Related Lessons" on http://pulitzercenter.org/projects/suggestible-you) (e.g. http://pccr.radcampaign.com/reporting/zika-virus-could-force-women-have-unsafe-abortions links to http://pccr.radcampaign.com/builder/model-lessons/using/17192 - same list, not tailored). Note from Danielle: not sure if this might be related to the "list lessons plans that are related to this node but also nodes that are related to this node" conundrum?

- [x] Education Resource tabs sitewide should pull relevant Lesson Plans (e.g. http://pccr.radcampaign.com/region/asia)

**Comment by xaqrox** [comment]
Point by point:
1. That is the term page for the taxonomy term "Lesson Plans" in the "Education" vocab. It's pretty sparsely populated, but that's really a content decision... do they want to be able to tag Ed. Resources with "Lesson Plans"?
2. Will be handled by new related lessons block.
3. :arrow_double_up: 
4. :arrow_double_up: 
5. This is exactly the same functionality (showing lessons directly referencing a nid) that's been on the LB since I built that page. The parent-child thing makes it hard (impossible?) to accomplish via Views, and right now Views is the only to get data into LB. Not sure how to handle this right now.
6. So lessons referencing any content tagged Asia, as opposed lessons tagged asia?

Overall, I would like to hear very precisely what makes a lesson "relevant". Might need to talk it thru.

**Comment by daniellerad** [comment]
1. Jeff said we can scrap the "Lesson Plans" term, and redirect education/lesson-plans to builder/community - how do we make this happen?

5. My brain hurts, so I'm typing this out the best I can understand it. Goal is to show 2 lists: 1) View Lesson Plans that reference this node; 2) View Lesson Plans that reference nodes that reference the Project that this node references

6. Just realized that Lesson Plans don't get tagged with the same metadata as other content like Stories or Projects. They get tagged with Subjects/Classroom Subjects and Topics/Tags. So, on the Topics pages (e.g. http://pccr.radcampaign.com/topics/religion), Lesson Plans tagged with the relevant terms should appear. On the Subjects page (e.g. http://pccr.radcampaign.com/subjects/social-studies), Lesson Plans tagged with the relevant terms should appear. I think you are right - they're wanting to pull in Lesson Plans that reference other content tagged with the terms. Similar as above, goal is to show 2 lists: 1) View Lesson Plans that reference this term; 2) View Lesson Plans that reference nodes that references this term. GAH. Let's chat about the complexities here.

**Comment by xaqrox** [comment]
1. Just delete the term and then create a redirect. But if the term is deleted it won't show on any nodes and I don't know how people would end up there.
2. :heavy_check_mark: 
3. ...ok...

**Comment by daniellerad** [comment]
Confirmed with Jeff - "See More Lesson Plans" can point to builder/community :)
