### ISSUE TITLE
taxonomy naming changes

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#263]
- [x] Topics -> Tags

- [x] Blogs -> Pulitzer Center Updates

- [x] Tags -> Content Groupings

- [x] Education -> Education Resources

**Comment by daniellerad** [comment]
Also, not a taxonomy term but a Content Type naming change:

- [ ] Gateway -> Issue

**Comment by xaqrox** [comment]
Won't it be confusing to have taxonomy vocabularies named "Pulitzer Center Updates" and "Education Resources" since we already have content types with those names...?

**Comment by daniellerad** [comment]
Yeah, so I think it's kinda the point that we want them to match. Because of the vocabulary labels on these term pages, it's unclear what "Education" or "Blog" are.

http://pccr.radcampaign.com/education/meet-journalists
http://pccr.radcampaign.com/blog/newsletter
