### ISSUE TITLE
Danielle's Deploy Tasks

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#268]
Primary links Menu:
- [x] Disable all the crap that's there now
- [x] Enable Reporting (reporting)
- [x] Fix /reporting path (which currently points at /taxonomy/term/1470 because of Reporting (Node Index) view
- [x] Enable Resources for Teachers (resources-for-teachers)
- [x] Enable Journalism Grants (grants)

Secondary links menu:
- [x] Add About (about-us)
- [x] Add Events (events)
- [x] Add Pulitzer Center Updates (pulitzer-center-updates)
- [x] Add Donate (donate) - ID must be donate

Footer Util menu:
- [x] Add Login (user/login)
- [x] Add Logout (user/logout)

Grantees menu:
- [x] Add Submit Content (node/add/story)

Add content to entityqueues:

Front Page Event Feature
- [ ]  A New Approach to the Middle East: Albright-Hadley Conversation at Washington University (20703)

Front Page Main Feature
- [ ] Who Are the Refugees Barred From Entering the United States? (20855)

Resources for Teachers: Lessons
- [ ] Migration and Refugees Lesson Plans (20360)
- [ ] Widowhood and Women's Rights (20653)
- [ ] World Religions, Science, and Beliefs (20866)

Resources for Teachers: Resources & News
- [ ] Hardy Middle Schoolers Report D.C., Slowly (20812)
- [ ] San Jose News Outlet Lauds California Education Initiative (20713)
- [ ] Bill Gates Cites Everyday Africa as Top Reason to Be Hopeful About Africa’s Future (20636)

**Comment by jselt** [comment]
@xaqrox re the Resources for Teachers menu

Is this dump enough to use? Or too much?

[resources-for-teachers.txt](https://github.com/radcampaign/pulitzer2016/files/761518/resources-for-teachers.txt)

**Comment by jselt** [comment]
Ok - here's a new one
[resources-for-teachers.txt](https://github.com/radcampaign/pulitzer2016/files/761549/resources-for-teachers.txt)

**Comment by jselt** [comment]
Ok - use this one
[resources-for-teachers.txt](https://github.com/radcampaign/pulitzer2016/files/761678/resources-for-teachers.txt)
