### ISSUE TITLE
media filter not filtering on taxonomy term pages

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#272]
Click on Media pulldown menu, choose any option, and click apply. Should filter for posts that contain that media type, but no dice. Doesn't filter anything. (Note: this functionality is working on Project pages.)

examples:
http://pccr.radcampaign.com/blog/education-news
http://pccr.radcampaign.com/subjects/journalism

**Comment by jselt** [comment]
I'm still stumped on this

I assume it relates to the JS error that appears on term pages but not views

This search turned up a few patches that I tried with no luck

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=top+undefined+drupal+ajax_views

I think it is related to caching and the dom id but I'm not having any luck
