### ISSUE TITLE
weird image hopping thing

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#277]
Jeff added an image (using Paragraphs) to this node:
http://pccr.radcampaign.com/reporting/testingtesting

The image did not appear on that node.

The image then appeared on this node:
http://pccr.radcampaign.com/blog/update-test

FYI - the image in question is the one with the woman and the puppy.

**Comment by xaqrox** [comment]
is there a step-by-step for this @daniellerad ?
