### ISSUE TITLE
views buttons path fixes

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#281]
Homepage:

- [x] "See more Pulitzer Center Updates" should go to pulitzer-center-updates (not blog)

- [x] "See more Issues" should go to ....missing this view page - referencing #109 

Resources For Teachers page

- [x] "See more Education Resources" should go to ....ummm, we might be missing a view page for all Education Resources :(

- [x] "See more Education News" should go to blog/education-news (not blog/education)

**Comment by jselt** [comment]
Gonna close the issues and education resources items - since the links aren't necessarily wrong. We just need to create the views.

Other ones I updated
