### ISSUE TITLE
misc grantee bugs

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#287]
http://pccr.radcampaign.com/node/add/story logged in as grantee

- [x]  Make caption required for each image uploaded. Title text may be better understood as "Image title text"

- [x] From PC: "I was able to save without a caption, but when i returned to it to add caption, feature froze and I was unable to scroll past the first box for "Alt text". I stretched my browser (i'm on a laptop) allowing me to see the field for "Title Text." I could also replace the image file. The caption field was not available/accessible, though the save button was."

- [x] Add audio - "An unrecoverable error occurred. The uploaded file likely exceeded the maximum file size (2 MB) that this server supports." File was 25 MB. Limit is listed as 40 mb where the upload is prompted, and should be 40MB.

- [x] If Grantees add an external URL, do no require a Word doc upload. (From Danielle: I have not tested this yet.)

- [ ] Location fields are missing - "Select the primary location of this content by the location link above." is there, but that's it.

- [x] Random images appearing on backend - maybe a misplaced context? Not sure where else this may be appearing. http://pccr.radcampaign.com/node/15337/edit?destination=dashboard/my-projects&content_lock_token=lL-YHOlS3t1Ukvhm4gaiX15KeX64-_5ohEbMkJkXkF4

**Comment by xaqrox** [comment]
All good, except:
> From PC: "I was able to save without a caption, but when i returned to it to add caption, feature froze and I was unable to scroll past the first box for "Alt text". I stretched my browser (i'm on a laptop) allowing me to see the field for "Title Text." I could also replace the image file. The caption field was not available/accessible, though the save button was."

"when I returned to it"... by clicking the "Edit" button after going thru the whole media browser workflow?

**Comment by xaqrox** [comment]
Location issue covered by #285
