### ISSUE TITLE
lesson builder search community lessons

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#295]
Xaq - we got this bug, but I wanted to note that we're supposed to implement the filters that we used on Reporting on the Lesson Builder...not sure what's the best order of operations here?

Lesson Builder -> Community Lessons. Enter search term "AIDS" to search for Lesson Plans that cover that topic.

In Lesson Builder search page I typed in "AIDS." I got some results that looked appropriate to query but the first result did not. It was a Lesson Plan based on SECCA exhibit in NC that features several of our photographer grantees. Here's the url for that lesson: http://pccr.radcampaign.com/builder/lesson/20079?referer=community.    Some other results that didn't fit the "AIDS" query term included a lesson based on Signs of Your Identity project by Daniella Zalcman and another on Cold War Fault Lines.    Results also included several results in what appear to be duplicate listings.

**Comment by xaqrox** [comment]
@daniellerad the same behavior is on the live site, shall we say not a launch-blocker?

**Comment by daniellerad** [comment]
Out of scope! Closing.
