### ISSUE TITLE
reporting keyword search stopped working after last night's deploy

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#297]
http://pccr.radcampaign.com/reporting

Search any keyword. Results are empty :(

**Comment by jselt** [comment]
Works fine locally. 

Triggered a reindex via drush on the staging server - may take a little while

**Comment by daniellerad** [comment]
Reindex didn't do anything. Also, somewhat related...is it possible to have the "enter" key trigger the "apply" for the filters?

**Comment by xaqrox** [comment]
@jselt you wanna stay on this?

**Comment by jselt** [comment]
Yeah sure. Can now reproduce locally - weird.
