### ISSUE TITLE
talks@pulitzer

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#308]
http://pccr.radcampaign.com/event/talkspulitzer-dominic-bracco-reporting-honduras-and-usmexico-border

They have these Talks@Pulitzer events, and the name is getting turned into a mailto link. Anything we can do about that? They said it's also ok to turn off all automatic mailto links, if needed. If this is not an easy fix, it's ok to push this one back to them as a content issue.

**Comment by xaqrox** [comment]
This is a bug in core, which I found the patch for. Turning off mailto links in general is more involved.
