### ISSUE TITLE
weird pagination control interaction on taxonomy term pages

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#309]
e.g. http://pccr.radcampaign.com/region/asia http://pccr.radcampaign.com/topics/religion

Go to pagination, and click "Next".

Clicking on any of the pagination buttons causes that button to shift down one line and widen.  After the page you're clicking to loads the button goes back to normal.

This isn't happening on Pulitzer Center Updates or Reporting - maybe it has something to do with the term page?

**Comment by jselt** [comment]
It's ajax paging - it brings up the little spinner. Has to be ajax paging in the tabs. Will see about the style. Don't want to just hide the spinner as that's bad for user interaction I think

**Comment by daniellerad** [comment]
Spinner is fine. I think he just doesn't like the button jumping around.
