### ISSUE TITLE
mobile - tabs on taxonomy term pages need some styling love

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#310]
http://pccr.radcampaign.com/region/europe

Look at this on a mobile device. Could line up a bit better, and needs some borders that are missing.

#265 is another quicktabs bug, if you want to knock out at the same time.

![image1](https://cloud.githubusercontent.com/assets/15112895/22791421/4d559ac0-eeb7-11e6-9305-6ecd2517f4c7.PNG)

**Comment by jselt** [comment]
We need a general style for tabs on at smaller breakpoints.

Thoughts? Kien?

**Comment by AlexandraCasser** [comment]
Should we do two rows of two sharing icons?  I think we should keep the other rows but extend them to full width.

**Comment by daniellerad** [comment]
Here's what I'm thinking - this is just for the 600px breakpoint and smaller, since above that looks fine (well, it's kinda crappy as 600px-632px, to be honest, so maybe break it there?). The RSS icon is going away (thanks #314 ) so that solves the two-row social problem. I've put border-radius of .4rem (all the way around) on all 4 <li> so they look more like clickable buttons instead of a row of tabs, and I've reduced the space around the Media exposed filter so that it doesn't take up so much room.

![mobiletabsmedia](https://cloud.githubusercontent.com/assets/15112895/22797518/8c5cfbcc-eecc-11e6-9d08-553f8f370ceb.jpg)

**Comment by AlexandraCasser** [comment]
Awesome.  Do you need me to implement that?

**Comment by daniellerad** [comment]
Actually, Jared just told me this won't work :( But we have another plan.

**Comment by AlexandraCasser** [comment]
Okie doke.  Let me know if I can help.
