### ISSUE TITLE
wysiwyg

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#313]
- [x] We discussed adding CKEditor instead of BUEditor.
- [x] We want to make sure that no WYSIWYGs get added to the Grantee node/add/story form.
- [x] Also, the WYSIWYG isn't appearing when you add text through Paragraphs. Click "Add Text" in Paragraphs. No WYSIWYG editor in the text field.  After you save the page and reload the editor, the WYSIWYG editor does appear.

**Comment by xaqrox** [comment]
@daniellerad Second item looks like it's already true, did they/you see this somewhere?
