### ISSUE TITLE
styling: Body Text and Paragraphs Text Doesn't Match

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#315]
Text created using Paragraphs Text boxes and Body text should be the same style. Body text is bigger and has looser kerning than text created with Paragraphs.

**Comment by AlexandraCasser** [comment]
Can this be done purely with CSS?

**Comment by jselt** [comment]
yeah - but I'm in the middle of a mix of edits I'll put this in. It's one line.
