### ISSUE TITLE
dashboard missing content & potential post migration problem

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#318]
http://pccr.radcampaign.com/admin/dashboard

I think that maybe PC Update, Story, and Education Resource may be missing from this list. (Usually Posts would be here but, alas, they are no more.)

Also...I did actually notice a bunch of old Posts...did they not get migrated correctly? They seem to be older ones.

Example: http://pccr.radcampaign.com/blog/news/africa-roundtable-pulitzer-center-director-jon-sawyer-washington-dc-april-20

**Comment by xaqrox** [comment]
Er, @jselt did you already do something about the first 2 lines of this issue?

**Comment by xaqrox** [comment]
closing in favor of individual issues #351 for dashboard, #352 for posts

**Comment by jselt** [comment]
I did as part of another isse

**Comment by xaqrox** [comment]
excellent.
