### ISSUE TITLE
reporting - publication filter bug

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#319]
Enter a two-word publication title into the publication field when those two words are not the first two words of the title. Example: Type "New York" but it doesn't find "The New York Times" because it's not the first two words.

If a user manually enters the exact title name starting with the first word, the publication search box will auto-complete and find that title. And even if the user starts typing a word out of sequence, it will work for the first word, but it breaks on the second word if those two words are not the first two in the title.

**Comment by xaqrox** [comment]
This is kind of solved, without this:
> And even if the user starts typing a word out of sequence, it will work for the first word, but it breaks on the second word if those two words are not the first two in the title.

Like "new books" -> The New York Review of Books? I don't think Chosen can do that. But e.g. "york review" will work.
