### ISSUE TITLE
grantee content isn't appearing in their dashboard

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#320]
I logged in as a Grantee, and added a story (http://pccr.radcampaign.com/reporting/danielles-test-grantee-submission), but it did not appear on my dashboard (http://pccr.radcampaign.com/dashboard). Sad day.

**Comment by jselt** [comment]
@xaqrox - you want me to takes this one?

**Comment by xaqrox** [comment]
sure- probably just updating the view for new content types. the view in question may not be in features yet.

**Comment by jselt** [comment]
it is not - adding now.
