### ISSUE TITLE
create related issues view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#33]

**Comment by xaqrox** [comment]
So there are many image fields on `gateway`:
- `field_image`&mdash;preview image in gateways view: http://pulitzercenter.org/gateways
- `field_background_image`&mdash;Big splash bg image (e.g. http://pulitzercenter.org/religion-and-power)
- `field_gateway_icon`&mdash;Terrible blue logotype things that are going away
- `field_header_image`&mdash;&mdash;OMG. It's the titles, next to the lesson builder buttons: http://pulitzercenter.org/land-rights this is made possible by some weird stuff in the old theme.

So the question is which of those fields is going to become the background of the squares?
![image](https://cloud.githubusercontent.com/assets/394919/19939472/8bcb67ea-a0ff-11e6-8695-090d80bda867.png)
The answer to this question probably depends on how we're going to support the not-yet-settled-on Issue layout. But my instinct is we should drop `field_gateway_icon` and `field_header_image` because they certainly have no place in the new design. And I think we should keep `field_image` because that field is shared with other nodes and if we ever want to show Issues mixed in with other content types it'll be handy. So really the question becomes do they need separate fields for the teaser/list view image and big splash image? Or can (should?) they be the same image exactly?

**Comment by xaqrox** [comment]
`field_image`!

**Comment by xaqrox** [comment]
ok so @jselt should I do the setting-image-field-as-background-on-row-element-in-preprocess thing for these?

**Comment by jselt** [comment]
yeah - thanks!
