### ISSUE TITLE
k-12 menu item disappeared from yellow bar menu

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#332]
http://pccr.radcampaign.com/resources-for-teachers

Pretty sure it was there after last night's deploy, and neither Jeff nor I touched it (no one else has menu access).

**Comment by jselt** [comment]
The path in the menu_changes.php script is `taxonomy/term/8171` - which does not exist. So the menu item would not have been created in all likelihood - or possibly the term was deleted by someone.

**Comment by daniellerad** [comment]
D'oh. I know what I did wrong. Will fix.

**Comment by jselt** [comment]
cloesed by #336
