### ISSUE TITLE
campus consortium sidebar - styling & remove past members

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#338]
http://pccr.radcampaign.com/campus-consortium

Sidebar needs styling to match the comp. Also, please remove the "Past Members" section from the bottom.

![pc-basicpage-final](https://cloud.githubusercontent.com/assets/15112895/22834487/4d1a9084-ef83-11e6-9f91-d37e7e8c8cce.jpg)

**Comment by AlexandraCasser** [comment]
I'm happy to take this if @jselt is busy.

**Comment by jselt** [comment]
Sure - thanks!

**Comment by AlexandraCasser** [comment]
No problemo.  😄

**Comment by jselt** [comment]
The past members can be removed in the view. I'll take care of that part - you don't need to hide it with css

**Comment by AlexandraCasser** [comment]
Awesome, thanks.  Do I need to enable to sidebar?

**Comment by jselt** [comment]
If you pull the latest from redesign, run `drush fra -y`, `drush cc all` - you should be up to date and a sidebar should be there on `/campus-consortium`
