### ISSUE TITLE
line breaks disappearing from body when a node is edited

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#341]
Earlier today, Jeff went in and added images to 4 nodes on the staging site so they wouldn't have missing images and his team could test with correct content.

Anyway, he just noticed that those same 4 nodes are now missing line breaks between paragraphs:
http://pccr.radcampaign.com/reporting/duterte%E2%80%99s-last-hurrah-road-martial-law
http://pccr.radcampaign.com/reporting/syrian-refugees-greece-are-moving-out-camps-and-new-kind-limbo
http://pccr.radcampaign.com/blog/washington-university%E2%80%99s-student-life-reports-hadley-albright-visit
http://pccr.radcampaign.com/blog/kbia-reports-narinx-hall-hadley-albright-visit

WYSIWYG problem? How do we fix this?

**Comment by jselt** [comment]
I think this may fix it

https://www.drupal.org/project/wysiwyg_linebreaks but haven't had a chance to test
