### ISSUE TITLE
lesson builder viewport issue?

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#343]
The Lesson Builder appears small and zoomed out on the staging site.

**Comment by jselt** [comment]
Isn't that just the font?

**Comment by xaqrox** [comment]
no...
* Live: 
![image](https://cloud.githubusercontent.com/assets/394919/22892225/d090e978-f1df-11e6-89a2-7f8d4d704b71.png)
* My local (with the right font): 
![image](https://cloud.githubusercontent.com/assets/394919/22892256/e7931eca-f1df-11e6-8f45-e42f0cc4c36a.png)

**Comment by jselt** [comment]
Boooo.

Is the lesson builder taking its html.tpl file from the active site theme?

**Comment by xaqrox** [comment]
No, `lesson_builder` defines its own

**Comment by xaqrox** [comment]
The bootstrap css is ending up in there somehow. The live site doesn't use any theme css as far as i can tell

**Comment by jselt** [comment]
Theme css is loading live actually - will throw an alter to make lesson builder load the old theme  - or no theme if it doesn't seem to need it.
