### ISSUE TITLE
HTML special chars in page aliases???

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#346]
e.g. the URLs in #341... how is that even possible?

**Comment by jselt** [comment]
Good question - I hadn't even noticed

**Comment by xaqrox** [comment]
Yeah pretty weird. Assigned you just to see if anything jumped out, I can look more into this later.

**Comment by jselt** [comment]
Maybe cause it's a curly single quote? Lemme check.

**Comment by jselt** [comment]
yeah - the transliterate option in pathauto settings is off - that converts those to ascii which then get filtered.

Easy enough to change, would have to delete and regenerate aliases to get them out of current ones.

**Comment by jselt** [comment]
See #347 for fix going forward

**Comment by jselt** [comment]
I'd probably leave the old ones intact for now - maybe go back to this post-launch?

@daniellerad - sound good?
