### ISSUE TITLE
Video embed code not rendering on event pages 

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#366]
http://pccr.radcampaign.com/event/pulitzer-center-web-site-launches 

Pasted video embed code into media module tab for embed. Video does not display on page.

**Comment by jselt** [comment]
we never really got clarity on what fields are supposed to be displayed going forward. This is one that is hidden. 

What else do they plan to use for Event nodes?

**Comment by jselt** [comment]
noting that a lot are hidden on the current site too

**Comment by jselt** [comment]
might as well get em all at once while I'm there ;)

**Comment by daniellerad** [comment]
I would think they would want Video/Images/Embed/Attachments to appear.

**Comment by daniellerad** [comment]
hmm...but if they're hidden on the current site, I can dispute.

**Comment by daniellerad** [comment]
Ah, so the video/image/embed appears in the view above the content on the current site...the attachment is shown below the event at the bottom (which is already working on staging: http://pccr.radcampaign.com/event/albright-hadley-middle-east-conversation-university-pennsylvania)

**Comment by jselt** [comment]
So video and embed - the images are handled by a view. We're not using views for a video/embed on other nodes - cause, well, that's pointless.

**Comment by daniellerad** [comment]
Yerp - sounds right to me.
