### ISSUE TITLE
RSVP button styling

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#376]
http://pulitzercenter.org/events

On the featured event in the hero, the RSVP button is whited out.  Mousing over, you can see the RSVP text, but the default state is just white.  The text is also aligned strangely on the button.

<img width="1282" alt="screen shot 2017-03-02 at 11 24 25 am" src="https://cloud.githubusercontent.com/assets/15112895/23516951/cf79cb1c-ff3c-11e6-998f-7a6cea0fb0a6.png">

**Comment by daniellerad** [comment]
Flagging this for tomorrow @xaqrox

**Comment by jselt** [comment]
Should really be for me no?

**Comment by daniellerad** [comment]
Sure!
