### ISSUE TITLE
paragraphs editor too wide for screen

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#377]
When you add content via paragraphs (PC Updates, Story, Education Resource), the text area extends way past the end of the browser window, making editing difficult. 

![screen shot 2017-03-03 at 3 34 53 pm](https://cloud.githubusercontent.com/assets/15112895/23568069/fed8b7ac-0026-11e7-81b1-9116a1a7463b.png)

**Comment by jselt** [comment]
Unable to reproduce in chrome, firefox, or safari on live site or dev site.

Can they provide more detail?

Browser, OS, screen size?
