### ISSUE TITLE
slideshow/sidebar overlap

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#379]
Between 767px - 991px, slideshows are overlapping on the sidebar. Examples:
http://pulitzercenter.org/reporting/yemens-silent-disaster-snapshot-life-and-death-rural-taiz
http://pulitzercenter.org/reporting/skin-deep-feeding-global-lust-leather

This only affects slideshows. Individual images react fine: http://pulitzercenter.org/reporting/people-smuggler-wanted-help-filipinos

![screen shot 2017-03-03 at 3 57 25 pm](https://cloud.githubusercontent.com/assets/15112895/23568790/33917c2e-002a-11e7-9077-938449db587f.png)

**Comment by jselt** [comment]
Will wait til they decide on #396

**Comment by jselt** [comment]
In PR #398
