### ISSUE TITLE
nav menus forcing capitalization

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#381]
http://pulitzercenter.org/about-us

In the bar menu, every word starts with a capital letter -- they would rather control the caps themselves. Capitalization should match what was entered in Drupal.

**Comment by jselt** [comment]
Do mean the sub-menu or main menus?

**Comment by jselt** [comment]
*Do they mean

**Comment by daniellerad** [comment]
This sub-menu :)

![screen shot 2017-03-15 at 1 08 15 pm](https://cloud.githubusercontent.com/assets/15112895/23961169/78c9dafc-0980-11e7-80f6-598ddbea28d9.png)

**Comment by jselt** [comment]
K - didn't know what "bar menu" means to them

**Comment by daniellerad** [comment]
lol fair

**Comment by jselt** [comment]
they're all in bars!
