### ISSUE TITLE
Remove Teaser/Summary from Home Page Hero Item

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#395]
We've found that the teaser/summary text in the home page hero item obscures the photo too much.  Nathalie has asked that we remove it.  Perhaps we could see it in dev before it's pushed into production?

**Comment by xaqrox** [comment]
![image](https://cloud.githubusercontent.com/assets/394919/24771091/4a2a8c58-1ada-11e7-9f8e-305a2d6c7008.png)

**Comment by xaqrox** [comment]
### Extra small
![image](https://cloud.githubusercontent.com/assets/394919/24774656/c94dc75e-1ae7-11e7-93a3-576b535bc7d9.png)

### Small
![image](https://cloud.githubusercontent.com/assets/394919/24774686/e0ca370a-1ae7-11e7-9af1-7244950fb43b.png)

### Medium
![image](https://cloud.githubusercontent.com/assets/394919/24774721/0147f40e-1ae8-11e7-89f8-46343d30ae73.png)

### Large
![image](https://cloud.githubusercontent.com/assets/394919/24774735/0d421b04-1ae8-11e7-92de-ba94ab42c186.png)

**Comment by daniellerad** [comment]
Awesome, will send for approval - thank you!

**Comment by xaqrox** [comment]
Check out new styles on http://pccr.radcampaign.com/

**Comment by daniellerad** [comment]
Looks good, except that the byline only shows at desktop, and disappears on tablet and mobile.

**Comment by xaqrox** [comment]
This should be ready but I'm out of time today, can deploy 1st thing tmw.
