### ISSUE TITLE
vertical image sizing

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#396]
From Jeff:

After vertical images are added to a story, page, update, etc., they're automatically cropped. This results in a poorly composed image, with faces cut off, for example. We need them to display these images in their original aspect ratio, even if that means that they're only the same height as the horizontal images.

Here's an example on the new site: http://pulitzercenter.org/reporting/young-heroes-living-hiv-malawi
And here's how it looked on the old site: http://dev.pulitzercenter.org/reporting/young-heroes-living-hiv-malawi

You'll note that the thumbnails were still a bit wonky on the old site, but the actual images are correct, though. 

(Note from Danielle - I'm not sure how this works with responsive. Let me know if we should discuss.)

**Comment by jselt** [comment]
Well it will push content down more and on those slideshows will cause some jumpy transitions. Not really a problem for responsive

Could add focal point so they can control the crop more or I can just change the image style to a scale instead of scale and crop. 

Are there other places this is an issue for them? I would need a list so I could make sure all the image styles are covered.

**Comment by daniellerad** [comment]
Asked :)

**Comment by jselt** [comment]
place your bets

**Comment by daniellerad** [comment]
From Jeff:

We’d like to scale the vertical images instead of scale and crop—my thought is that all images should be the same height, so if we had a vertical image, it would be the same height as our standard horizontal image, only it would be centered in the image space, with white bars on either side (hope that makes sense). Instagram-style square images will also need to be styled the same as vertical images.

I’m assuming that once the fix is in place, it will work retroactively as well as for any future vertical images?

The only real instances of vertical images showing up are on stories, updates and events. We don’t want to change the image styling on the pages that list reporting and updates (Reporting, Education, Project landing pages, etc.), our preference is to stick with purely horizontal thumbnails and do a manual crop in the rare instances when it’s necessary. Basically, we want the vertical images to behave exactly like they did on the old site, if that’s helpful.

**Comment by jselt** [comment]
That's a terrible idea - they should scale to the same width not height - also this would take longer as it involves redoing more styles.

Do they understand what focal point is?

**Comment by daniellerad** [comment]
Idk. However, on their old site, you could click on an image in the slideshow, and it would open a lightbox so you could see the full image. We don't have that on this site, so I understand that they need some way to display the full non-cropped image.

**Comment by jselt** [comment]
Ok - how much maintenance do they have?

**Comment by daniellerad** [comment]
Green light to scale to the same width.

**Comment by jselt** [comment]
Well it's not going to work so well as they upload enormous images.

They won't accept a crop even if they have some control?

**Comment by daniellerad** [comment]
Hmmm. I think they are open to ideas as long as there's a way for the user to view the entire vertical image.

**Comment by jselt** [comment]
well - the only way that's workable is with a lightbox.

The problem with scaling to a vertical height with a proportional width is that no image will ever scale all the way to the size of the column. Which is what makes the layout look nice and scannable.

We can do a lightbox but they do not have the hours in maintenance unless we're sitting on a 20ish hour pile. The way images are handled now are much different.

I'm curious as to why they are insistent on full images when most of these are head shots where the full image is just extraneous setting.

**Comment by daniellerad** [comment]
Their photos are very important to them because they are part of the work of the journalist.

**Comment by jselt** [comment]
Then I would say use focal point with a lightbox.

**Comment by jselt** [comment]
BUUUT - they can't upload images that are 4000x3000 in that case and expect that to work well. Particularly in a lightbox.

They need to limit the size uploaded images.

**Comment by daniellerad** [comment]
Ok, that's not approved at this point. They only approved the 1-hour to scale to the same width.

They will not be able to limited the uploaded image sizes because this is their archive. This is where journalists send Pulitzer their content.

**Comment by jselt** [comment]
They aren't posting the images directly to the story though. When they create the story they need to work on the images before adding them.

I can discuss this with them if you prefer.

**Comment by daniellerad** [comment]
That's not their workflow, but feel free to discuss with Jeff on this thread: https://radcampaign.basecamphq.com/projects/13482568-pulitzer-monthly-maintenance/posts/101869964/comments#364067773

**Comment by jselt** [comment]
will do

**Comment by daniellerad** [comment]
I say go ahead and do this, if there's time, Jared. I'll make sure we get some hours pre-authorized.

**Comment by jselt** [comment]
Okey dokey

**Comment by jselt** [comment]
@daniellerad  Well, here's the best I can do I think - if you have edits lemme know.

Image style is now scale to 510 height, proportional width, no upscaling

http://recordit.co/q3lPReeVk3

http://recordit.co/G9HBAbQVda

**Comment by daniellerad** [comment]
Thanks Jared - this is helpful. I think it looks good. I'll send these to Jeff and get his thoughts.

**Comment by jselt** [comment]
No one can resist puppy Lita

**Comment by daniellerad** [comment]
OMG that's puppy Lita?!?!

**Comment by jselt** [comment]
Yeah - I just uploaded an image at random from Dropbox - which my phones have synced with since forever. It happened to be Lita on her second day with us

**Comment by daniellerad** [comment]
😍 😍 😍 😍 😍

**Comment by daniellerad** [comment]
@xaqrox When you have a chance, please left-align the captions (instead of center). Note from Jared: "Should be just one line in shared.scss - just remove text-center from whatever the caption div class is."

Once that's done, we can deploy. Thanks!

**Comment by jselt** [comment]
In the nodes subdirectory of the sass foldef

**Comment by jselt** [comment]
Actually, looking here on my phone you'll need to add text-align:left to .field-name-field-image-caption

**Comment by daniellerad** [comment]
Hey @xaqrox would you mind making this change and pushing this live this afternoon?

**Comment by xaqrox** [comment]
@daniellerad does this look right? pccr.radcampaign.com/reporting/young-heroes-living-hiv-malawi

**Comment by daniellerad** [comment]
Captions under the photos still look centered to me - should be left-aligned.

**Comment by xaqrox** [comment]
it is done.
