### ISSUE TITLE
LB search filters: would like "more search options" to stand out more

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#400]
I can figure out some styles for this.

**Comment by daniellerad** [comment]
![screen shot 2017-04-20 at 1 48 34 pm](https://cloud.githubusercontent.com/assets/15112895/25244954/c11738ec-25d0-11e7-9971-4595a814743f.png)

![screen shot 2017-04-20 at 1 50 44 pm](https://cloud.githubusercontent.com/assets/15112895/25244953/c112b11e-25d0-11e7-99d9-c4ea51ee836f.png)

**Comment by daniellerad** [comment]
Green light from Jeff on these styles.

**Comment by xaqrox** [comment]
Is that gree color elsewhere on the site or do you have a hex for it @daniellerad?

**Comment by daniellerad** [comment]
#51cfc0
