### ISSUE TITLE
LB: author list drop-down

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#407]
Compromise between current author list and listing all authors:

Please add a checkbox to the each individual user profile on the Drupal backend that allows you select "Appear on Lesson Builder Community Lessons Author drop-down" - PC will check that for each individual who should appear in the Authors drop-down filter.

**Comment by daniellerad** [comment]
This looks great - Jeff's only question was if they could be list in alphabetical order.

**Comment by xaqrox** [comment]
By last name?

**Comment by daniellerad** [comment]
By whatever is possible - I didn't know if it was one name field or split into first/last.

**Comment by daniellerad** [comment]
First plz

**Comment by xaqrox** [comment]
For some reason the view is not respecting sort settings *at all* and IMHO there is no point in debugging it because:
1. you'll probably be able to see all the options
2. sorting by last name is totally reasonable
3. this is going away in a couple months anyway

**Comment by daniellerad** [comment]
Okie dokie. So, it's sorted by last name now?

**Comment by xaqrox** [comment]
Yep

**Comment by daniellerad** [comment]
Good with Jeff. Closing.
