### ISSUE TITLE
Multiple Publications for Single Story

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#410]
The old site was able to accommodate multiple publications for a single story—the new site is not set up to do this. In some cases, the same story will appear through multiple publishers. We need to reflect this by being able to add multiple publications to a single story. Here is a recent story with multiple publications: http://pulitzercenter.org/reporting/honduras-defending-nature-deadly-business

**Comment by jselt** [comment]
They can do this still

![drought in hamoon lake pulitzer center](https://cloud.githubusercontent.com/assets/1815689/26254507/cbed65b4-3c84-11e7-9661-cdf77ed1b62d.png)

![drought in hamoon lake-view](https://cloud.githubusercontent.com/assets/1815689/26254509/ce8a6f7e-3c84-11e7-85c7-bc17c01664cc.png)

**Comment by daniellerad** [comment]
Woot. Thx.

**Comment by daniellerad** [comment]
http://pulitzercenter.org/reporting/honduras-defending-nature-deadly-business

Ah, ok so the real issue is that, in the Publication block on the sidebar, only one external Publication link is being used. On the example above, the Guardian logo and "View this story on the Guardian" still link to Yale.

**Comment by jselt** [comment]
Ahhhh - cause there is only one external url field.

So really what they need is a repeatable paragraph field with a single select dropdown for the Pub name and a url field.

That's a slightly more involved change, but not a huge deal for next week.

Though I wonder how (if) that worked before.

**Comment by daniellerad** [comment]
Sounds good. I'll tell Jeff we can do it next week.

**Comment by xaqrox** [comment]
Curious if they can find an example on http://dev.pulitzercenter.org

**Comment by jselt** [comment]
You mean one that supports multiple links? Would be easy to see if I could log in. But can't seem to - can you?

**Comment by xaqrox** [comment]
nope. that's pretty weird.

**Comment by xaqrox** [comment]
yeah it never did. it just displayed multiple publication terms, but only ever one link http://dev.pulitzercenter.org/reporting/humanitarian-and-protection-disaster-refugees-greece

Just want to flag that if we change the way this works we should probably migrate the old content too.

**Comment by daniellerad** [comment]
Good thought. I'm guessing that will up the hours past what we have remaining in May?

**Comment by xaqrox** [comment]
Maybe could *just* squeeze it in

**Comment by daniellerad** [comment]
Ok, let me look at the workload for this week and get back to you tomorrow.

**Comment by xaqrox** [comment]
Actually tho, adding another step between stories and their publication is gonna force changes on other things, like how the reporting search works, and the publications term pages...

**Comment by daniellerad** [comment]
Ok, that's good to know. Let's definitely put this on hold until June, and I'll talk with Jeff about priorities here. I can queue up something small for this week, or roll over his remaining ~3 hours to June.

**Comment by daniellerad** [comment]
Hey @xaqrox - circling back on this. We can start on this again. We might also need to fix this on Events. (Not sure...Jeff was vague.)

**Comment by xaqrox** [comment]
The Publication term and link fields only exist on Story, so if something on Event needs fixing Jeff will have to be more specific.

**Comment by daniellerad** [comment]
Deal. Let's move forward with the fix on Story.

**Comment by jselt** [comment]
This? https://radcampaign.basecamphq.com/projects/13832106-pulitzer-lesson-builder/posts/102423182/comments#366641041

That's a different issue -projects, not publications.

**Comment by daniellerad** [comment]
Ah you are totally right. Will open a separate GH issue.

**Comment by daniellerad** [comment]
PCCR staging fix works for Jeff with a few tweaks:

1. Make sure the style of the logo and the link text for the second publication matches the style of the first publication.

2. If possible, limit to 2 or provide additional help text directing people not to add more than 2 because it breaks the layout. (Or, if easy, fix the layout so it doesn't break.)

![screen shot 2017-05-31 at 10 42 53 am](https://cloud.githubusercontent.com/assets/15112895/26637660/1b3a10fa-45ee-11e7-88a7-65fe0c65fbe8.png)

**Comment by xaqrox** [comment]
Link to this story?

**Comment by daniellerad** [comment]
http://pccr.radcampaign.com/reporting/humanitarian-disaster-refugees-greece

**Comment by xaqrox** [comment]
Twas a bug. Good now.
