### ISSUE TITLE
Implement "Print this Lesson Plan" button

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#424]
A “Print this Lesson Plan” button will launch the print dialog. A minimal print stylesheet will be preserved.

**Comment by daniellerad** [comment]
Note from client:
The full webpage prints, including the headings for the webpage and Jeff's contact information. Would like to only have the relevant content print (perhaps hide the header and footer from the printer style sheet).  It should provide a clean print-out of the lesson.

**Comment by daniellerad** [comment]
Hey @jselt assigning this to you - please see the client note in my comment above.

**Comment by jselt** [comment]
http://pccr.radcampaign.com/builder/lesson/terrorism-and-tourism-maldives-23020

:man_shrugging:

**Comment by jselt** [comment]
Whoops - @daniellerad go to http://pccr.radcampaign.com/builder/lesson/terrorism-and-tourism-maldives-23020

And hit the print button

:man_shrugging: ?
