### ISSUE TITLE
Embed survey monkey block

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#429]
In context or template?

**Comment by daniellerad** [comment]
https://www.dropbox.com/s/wzoj4b56yyzrmcn/pc-survey-monkey-embed.htm?dl=0

**Comment by xaqrox** [comment]
@daniellerad do we have their login?

**Comment by daniellerad** [comment]
we don't - do you need it?

**Comment by xaqrox** [comment]
don't know for sure, but can't hurt. if i need to add a field or something to pass the URL. /just to poke around and see how it works in the first place.

**Comment by daniellerad** [comment]
np. asked.

**Comment by jselt** [comment]
https://help.surveymonkey.com/articles/en_US/kb/What-are-custom-variables-and-how-do-I-use-them

FYI

**Comment by daniellerad** [comment]
Jeff gave a green light for the Drupal webform alternative.
