### ISSUE TITLE
create hompage Issues carousel view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#44]

**Comment by xaqrox** [comment]
@daniellerad: How should these be sorted? and should they be limited by "promoted to front page"?

**Comment by xaqrox** [comment]
Still needs carousel magic. After styling?

**Comment by jselt** [comment]
Prolly just add some javascript

**Comment by xaqrox** [comment]
I was thinking we'd use slick, since we need a fancy plugin for the img slideshow anyway...?

**Comment by jselt** [comment]
that works

**Comment by xaqrox** [comment]
Or were we just going to keep using cycle for that? In which case I could probably get that working here too.

**Comment by jselt** [comment]
Either is fine with me. If we do cycle we need to use cycle2 for swipe.

**Comment by xaqrox** [comment]
:boom: Slick works. Just needs some style attention now.
