### ISSUE TITLE
advanced search results - styling

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#446]
PC would like to make some style tweaks to the advanced search results page on Pulitzer Center.
(http://pulitzercenter.org/advanced-search?search=philmont&op=Search). Right now, each item is crammed against another, making it difficult to determine which photos and summaries go with which item. Here's the approved comp:

![pc-advancedsearch-r1](https://user-images.githubusercontent.com/15112895/27875152-3b288ae2-6180-11e7-801b-cb385d658a97.png)

**Comment by jselt** [comment]
How are they getting to this? This is a view page that has been retired.

**Comment by daniellerad** [comment]
Do a search from the header. The Search Results page it takes to you still has "Advanced search" options.

**Comment by jselt** [comment]
Not the same page/thing

**Comment by daniellerad** [comment]
Jeff isn't sure how it was found. Ok to hide/delete.

**Comment by jselt** [comment]
Ok - done
