### ISSUE TITLE
old lesson URLs should 301 to new URLs

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#451]
e.g.
http://pccr.radcampaign.com/builder/lesson/22752
http://pccr.radcampaign.com/builder/lesson/22752?referer=community
should redirect to ->
http://pccr.radcampaign.com/builder/lesson/women-learning-and-practicing-law-saudi-arabia-22752

**Comment by daniellerad** [comment]
Re-opening and flagging this since it's not working on the staging site. Is this one of those things that takes a database rebuild or something like that?

**Comment by xaqrox** [comment]
All set!
