### ISSUE TITLE
very bizarre summary character limit behavior

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#454]
Log in to Pulitzer Center website -> Create Story/Education Resource/PC Update (something with a summary with a character limit).

Type content into the summary field. Then delete words, and you'll see the character count increases (it should decrease it words/characters are deleted).

**Comment by xaqrox** [comment]
That's characters left, not characters total...

**Comment by daniellerad** [comment]
Ok that is very strange bc I think that flew totally over my head.

**Comment by jselt** [comment]
Maybe add "left" after the numbers?

**Comment by daniellerad** [comment]
Nah, no need. I feel silly for not catching that this morning. It was their intern who noted the problem so nbd.
