### ISSUE TITLE
Add language to "no results found" page

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#469]
“If your search turns up empty, try our regular search page, for access to thousands of Pulitzer Center stories, videos and photographs."

**Comment by xaqrox** [comment]
Should this link to the search page and if so do you think they mean http://pulitzercenter.org/reporting or http://pulitzercenter.org/search/node?

**Comment by daniellerad** [comment]
They didn't ask for it to link so I say don't link for now.
