### ISSUE TITLE
swap in new image on homepage Lesson Builder teaser

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#470]
The large yellow callout on the PC homepage will need a new LB image.

**Comment by daniellerad** [comment]
https://www.dropbox.com/s/96p0dkk88hxvjtv/pc-home-LBdesktop-graphic.png?dl=0

**Comment by jselt** [comment]
http://pccr.radcampaign.com/

Same image in the code - so this updated when I updated the ED page - was it smaller before tho?

**Comment by daniellerad** [comment]
I don't think so...I used the same PSD to edit it. Not sure why it's being wonky on the homepage but I see what you mean.

Also, here's the new teaser text for this area:
`The Pulitzer Center offers hundreds of free Common Core aligned lesson plans based on original global reporting from news outlets such as <em>The New York Times</em>, <em>PBS NewsHour</em>, <em>The Washington Post</em>, <em>The New Yorker</em>, NPR, and many more. Lesson plan topics range from refugees to climate change to women and children's issues.`

**Comment by jselt** [comment]
I'll just scale it down a bit in the box.

**Comment by jselt** [comment]
See http://pccr.radcampaign.com

**Comment by daniellerad** [comment]
Oh would you mind making sure the text doesn't get hidden behind the image at 990px-1199px(ish)?

Thank youuuuuuu.

![screen shot 2017-08-14 at 1 25 25 pm](https://user-images.githubusercontent.com/15112895/29283322-3f88703c-80f4-11e7-813c-8c050ca7a1a5.png)

**Comment by jselt** [comment]
http://pccr.radcampaign.com/
