### ISSUE TITLE
create reporting view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#48]
[Functional Requirements](https://docs.google.com/document/d/1LMVo94yb8ibPW1sUJK5pB36BMX-zuMgy53vbAOAAyH4/edit#) sez:

The redesigned Reporting section will keep its name, but will be streamlined to provide intuitive interfaces for users to stay up to date on the reporting by grantees, and to browse and search the archive of stories and projects.

This page would show all Posts ("Stories") (using pagination), sorted by most recent first. There could be a toggle or tab to allow users to view the Posts ("Stories") grouped by project. The Post list could then be filtered/searched by:
- Keyword
- Publication
- Type of Media (Media taxonomy reference)
- Region
- Country
- Post Date
- Gateway (name TBD)
- Author

Posts ("Stories") and Projects will be visually differentiated to reflect their specific role in the hierarchy of PC’s reporting content.

**Comment by daniellerad** [comment]
Noting the language for the search results numbers: we proposed changing the language to match the interaction. So, to start, it would say "of 210 stories." (or projects), and then it would change to "of 210 stories matching the criteria."

**Comment by xaqrox** [comment]
@jselt how would you recommend implementing this layout. bootstrap views? it's different from the homepage because each view is a column but now we need rows within a single view... I tried just putting the column class on the views "row" (i.e. around each teaser) but they floated all messy.
![pc-reporting-final](https://cloud.githubusercontent.com/assets/394919/22256183/fccc2cb8-e227-11e6-8657-53e6fcca0ebc.jpg)
