### ISSUE TITLE
request a lesson form

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#480]
I think Xaq built a dummy webform - does a new webform with the correct fields need to be added on the live site? Or do we add these fields to the existing webform on the staging site? I can probably help with this, if needed. Let me know.

http://pccr.radcampaign.com/builder/request

Request a lesson form should include the following fields:
Headline: Request a Lesson
We want to partner with you to create new lessons for the Pulitzer Center Lesson Builder. 
First Name
Last Name
Email Address
Grade Level/Organization Role (checkboxes): Elementary, Middle School, High School, College, Other 
Other Grade Level (Enter Textbox)
Please enter the details of the lesson you'd like built in the field below:
Text area
Submit Button

**Comment by daniellerad** [comment]
i can prompt them to create the webforms on the live site - is that what needs to happen?

**Comment by jselt** [comment]
I assume so - but I have no idea what @xaqrox has set up, so I'll ask when he gets in.

**Comment by xaqrox** [comment]
This form already exists on the live site, though with a different alias. In `lesson_builder.install` there is an update hook that publishes all the webforms, updates their aliases and gives them menu items. You can edit them on the live site and when the updates run they'll end up where they need to be. You can take care of #481 this way also.

**Comment by jselt** [comment]
Cool - thanks

**Comment by jselt** [comment]
http://pulitzercenter.org/do-not-delete-request-lesson

Added the fields here.
