### ISSUE TITLE
webform notifications

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#481]
There are 3 webforms, and each should have notification rules that sends an email to education@pulitzercenter.org on submission.

http://pccr.radcampaign.com/builder/request
http://pccr.radcampaign.com/builder/feedback
http://pccr.radcampaign.com/builder/survey

**Comment by jselt** [comment]
I added email notifications to the request and survey forms

On the feedback form there are already some notifications set up - do they want an additional one or just repoint one of the existing? http://pulitzercenter.org/node/16924/webform/emails
