### ISSUE TITLE
LB changes needed on education page hero

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#482]
http://pccr.radcampaign.com/education

Since users will not be able to create lessons, please remove the "Create" section from the hero area on the Education page. Maybe move the "Search" copy over to where "Create" is now?

We also need to swap out the image with a new screenshot of Lesson Builder - do you want me to create that and send it to you?

**Comment by daniellerad** [comment]
https://www.dropbox.com/s/96p0dkk88hxvjtv/pc-home-LBdesktop-graphic.png?dl=0

**Comment by jselt** [comment]
@daniellerad http://pccr.radcampaign.com/education
