### ISSUE TITLE
showing past events on project pages

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#483]
(This is the low-priority maintenance item for August.)

As you can see in the sidebar on this page, Events that reference a Project do appear on the Project page:
http://pulitzercenter.org/project/asia-china-beijing-rat-tribe-migrant-workers-poverty-service-poor-housing

However, the sidebar block only currently shows upcoming Events. Pulitzer Center would like to find a way to show Recent (past) Events because: 1) this provides examples for users of the types of Events that Pulitzer can host, 2) this provides action/impact info for funders, and 3) this provides a quick reference for Pulitzer staff who are do project-based funder reports.

Ideas:
1. They would be open to keeping the Recent Events in the sidebar (maybe with some sort of distinguisher) - it is important to note that some projects (like http://pulitzercenter.org/project/fractured-lands) have a bunch of Related Events. Make sure to use that as a use case during testing.

2. Add another tab to where Stories/Education Resources/Pulitzer Center Updates already live...not sure if there is space for this and/or if it would make the tabs seem less tab-y?

3. Open to your thoughts if you have other ideas?

Whatever we do, we'll need to get Jeff & Nathalie an hours estimate first.

**Comment by xaqrox** [comment]
What about another block in the sidebar that lists recent events styled more like the related lesson plans? Just a date and title? Maybe show up to 5? That would take about 1.5h.

The tab could work too but it seems like they don't belong there.

**Comment by daniellerad** [comment]
That's fine to show up to 5, though they will want a way to see all of them (whether that means they're all listed on the sidebar, or if they click through to a filtered page of events).

**Comment by xaqrox** [comment]
Just FYI, it appears Fractured Lands has 2 related events.

**Comment by xaqrox** [comment]
Whoops nevermind
