### ISSUE TITLE
survey form - link back to current page

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#484]
http://pulitzercenter.org/node/23159/webform/configure

Right now, after you submit, there's a link to "Go back to the form" that takes you to the survey node page. They'd like to remove that, and prompt people to go back to the lesson they were on.

Or, maybe it's best to simply remove the "Go back to the form" link and set the redirect location on the webform to "No redirect (reload current page)"?

**Comment by jselt** [comment]
Changed it to no redirect on the live form.
