### ISSUE TITLE
add last updated date to bio pages

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#486]
They'd like to add "Last Updated on DATE" to bio pages, just below the bio text.

Given that bios go out of date so quickly, they think it would be nice for visitors to be able to see how old they are. Here's an example of the page type: http://pulitzercenter.org/people/jon-sawyer

**Comment by jselt** [comment]
That's problematic as Drupal doesn't track when a user has updated their profile (at least when using the core user entity which pulitzer does).

We'd have to first set up tracking profile modifications and they would probably all start from whenever we set up that tracking, so much of them wouldn't be very worthwhile.

**Comment by jselt** [comment]
Ugh "most of them". 

Much of them 😬

**Comment by daniellerad** [comment]
Ahhh yeah you are so right. Will go back to Jeff.

**Comment by jselt** [comment]
We can do it - but it will take longer maybe an hour or two and they would all start out with the exact same date until they were updated.

**Comment by jselt** [comment]
I assume they figured it would just be a few minute job

**Comment by daniellerad** [comment]
Yep. You're probably right. I also gave him the option of just adding a date field, and they can manually add/update the date for each user.

**Comment by jselt** [comment]
If we do it, my thought was we would add a date field, restrict form access to it to only admins or something and then automatically update it with the current date using hook_node_save. Unless @xaqrox has a better idea.

**Comment by xaqrox** [comment]
`hook_user_save`, but yeah that makes sense

**Comment by jselt** [comment]
Doh 😬

**Comment by xaqrox** [comment]
Or really, this one https://api.drupal.org/api/drupal/modules%21user%21user.api.php/function/hook_user_presave/7.x

**Comment by daniellerad** [comment]
They'd like to go the manual route by adding a date field to Drupal user profiles, and the PC team will add in dates (and update dates) for each profile manually. Any profiles that don't have dates selected shouldn't show anything on the front end.

**Comment by jselt** [comment]
Ok - do dumb thing in dumbest way possible. Check ;)
