### ISSUE TITLE
Hide private lessons from search

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#487]
Not sure if this got done? All Lessons that are not marked as "Public" should be hidden from search indexing.

**Comment by xaqrox** [comment]
It did, theoretically, in this commit &mdash; 6c38d778

**Comment by daniellerad** [comment]
Here are two lessons that do not have "Public" checked, and still have '<meta name="robots" content="follow, index" />'

**Comment by xaqrox** [comment]
Ah. I misread your comment above. Yes that needs to be dealt with.

**Comment by daniellerad** [comment]
K thx

**Comment by xaqrox** [comment]
Done, confirmed on the nodes linked above.
