### ISSUE TITLE
create resources for teachers submenu area

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#50]

**Comment by jselt** [comment]
did we say we were going to just use Font Awesome icons? or do I need to allow them to upload icons images?

Doesn't matter much to me - just checking

**Comment by xaqrox** [comment]
I think we determined that FA doesn't cover these. at least a cursory search didn't turn anything up

**Comment by jselt** [comment]
Ok - menu icon module it is

**Comment by xaqrox** [comment]
Icons are weirdly large on beta http://pccr.radcampaign.com/resources-for-teachers

**Comment by jselt** [comment]
Looks like they're being upscaled.

**Comment by jselt** [comment]
Sorted.
