### ISSUE TITLE
create featured pc update view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#62]

**Comment by jselt** [comment]
@xaqrox @daniellerad is there a specific way we are determing what is "featured"?

Queue, sticky,...?

**Comment by daniellerad** [comment]
However it's happening on Events works for me. As long as the process is consistent, I'm good.

**Comment by jselt** [comment]
well that hasn't been built yet either - so...

**Comment by daniellerad** [comment]
lol entityqueue then?

**Comment by daniellerad** [comment]
that's how other stuff is going up on homepage and resources for teachers, so it gets consistency points from me

**Comment by jselt** [comment]
ok - the blog on the current site is just ordered by sticky and then date - just checked

**Comment by daniellerad** [comment]
awesome - good call

**Comment by jselt** [comment]
k

**Comment by jselt** [comment]
How do we want to handle the background image for this? - I think the one in events is the same one used in resources for teachers - probably want some variation, no?

**Comment by daniellerad** [comment]
I can definitely get you a new image. Feel free to use the same image to unblock yourself, and then I can ask PC next week.

**Comment by jselt** [comment]
Well - I wonder if we should add a way for them to manage these via theme settings? Do we know how many of these there are?

**Comment by daniellerad** [comment]
i think this might be it?

**Comment by jselt** [comment]
So 3?

Not a big deal to do

**Comment by daniellerad** [comment]
I'm not 100% sure but I can confirm on Monday. Either way is fine with me.

**Comment by jselt** [comment]
ok, I'm fine with css but we can give them flexibility

**Comment by jselt** [comment]
@daniellerad - no rush - but should I build out some functionality for this or just do with css and punt?

**Comment by jselt** [comment]
I know the football speak

**Comment by daniellerad** [comment]
Lol 🏈 

Sorry, this totally slipped my mind yesterday. Let's do this with CSS for now. I'll let them know that additional functionality is possible if they need to switch out images often.

**Comment by jselt** [comment]
Yesterday got kinda hectic - np.
