### ISSUE TITLE
create pc updates landing view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#64]

**Comment by daniellerad** [comment]
Should look like Events landing.

Filters on wireframe: keyword, author, posted date (range), media types, categories? Danielle will confirm these are appropriate.

**Comment by daniellerad** [comment]
These are correct. The date should be publish date, I believe. Categories are from the Blog taxonomy.

**Comment by jselt** [comment]
@daniellerad Image, date, byline, teaser?

**Comment by daniellerad** [comment]
👍  can be same fields as pulitzer center updates on homepage (those 4 things plus title and blog category)

**Comment by jselt** [comment]
k - should the url still be blog?

**Comment by daniellerad** [comment]
/pulitzer-center-updates with /blog as a redirect or alias

**Comment by jselt** [comment]
okey dokey

**Comment by daniellerad** [comment]
hmmmm actually does that make sense with the URL structure of pulitzer center updates

http://pccr.radcampaign.com/blog/pulitzer-center-grantees-finalists-2017-ellie-awards

will the newly created content be /pulitzer-center-update/... ?

**Comment by jselt** [comment]
well we can change all the aliases for the update nodes

**Comment by jselt** [comment]
and redirect should automatically add redirects

**Comment by daniellerad** [comment]
ah ok awesome then

**Comment by jselt** [comment]
Many of these don't have published_date values - I'll leave off the date filter for now. 

Probably related to #236
