### ISSUE TITLE
create fbshare/twitter/email buttons

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#87]
![image](https://cloud.githubusercontent.com/assets/394919/19947015/9e8e3d0e-a11c-11e6-9f91-fc002a0982ed.png)

**Comment by xaqrox** [comment]
I'm not sure where this came from but it looks like we're not using the usual floating-on-the-side-of-the-window thing. I'm going to rename this to cover the sharing buttons on the story/resource/update pages and move this to the Story milestone.

**Comment by xaqrox** [comment]
@jselt you mentioned there was a good way to do this that would let it be nicely styleable (for twit&fb)... also any ideas about the "Email" button? Complicated `mailto:` link? Some service? @daniellerad?

**Comment by jselt** [comment]
We can use addthis for this - just disable the stylesheet in settings and then style as needed.

We can keep sharethis too - just take a little longer to override the styles in that case. 

No real preference from me.

**Comment by xaqrox** [comment]
@daniellerad do we know their sharethis publisher key?

**Comment by daniellerad** [comment]
...they have no idea what that is. They may not even use it? 

http://pulitzercenter.org/admin/structure/block/manage/block/7/configure looks like basic links, and the header SM is a menu.

Do you want me to ask them to set one up?

**Comment by xaqrox** [comment]
Oy. Just having some trouble with the sharethis module and have console message asking for the publisher key, hoping if i provide that it'll make the darn thing actually show up. So... yes?

**Comment by xaqrox** [comment]
Or i can make a dummy acount to test with first

**Comment by daniellerad** [comment]
Np, will do.

**Comment by xaqrox** [comment]
@daniellerad do we know if it's actually important to them to have tracking for these things? getting buggy sharethis module to work is sucking time and wondering if it wouldn't be faster/wiser to just build some basic stuff to accomplish this, if we don't need analytics

**Comment by daniellerad** [comment]
ok to backburner for now! feel free to use existing code.

**Comment by xaqrox** [comment]
@jselt did this
