### ISSUE TITLE
figure out how status emails are generated

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#9]

**Comment by xaqrox** [comment]
I found it! http://pulitzer.dev/admin/config/workflow/rules/reaction/manage/rules_status_email/edit/3 It is pretty gnarly, embedding views via php in rules config. What's more, it's inactive. When's the last time anyone received one?

**Comment by daniellerad** [comment]
I'll ask. I think the plan should be to keep as-is and simply make sure they don't get lost.

**Comment by daniellerad** [comment]
Jeff says he receives 2 every morning, so maybe this isn't it...?

**Comment by xaqrox** [comment]
True. It's this one http://pulitzer.dev/admin/config/workflow/rules/components/manage/24

**Comment by daniellerad** [comment]
Related update from Jeff on 1/5 (https://radcampaign.basecamphq.com/projects/13482568-pulitzer-monthly-maintenance/posts/100921849/comments) - kinda half main site, half maintenance?

Right now only the title is displaying under the "Published" section -- we also need the author(s) name(s) and the Publication Date/Time.
We'd like to remove Lesson Plans from the "Published" section.
We'd like to create a new "Lesson Plans" section that lists all published (non-draft) lessons.

**Comment by xaqrox** [comment]
Are these new (post-rebase) issues or enhancements?

**Comment by daniellerad** [comment]
I believe it's a bit of both. Do you want me to confirm?

**Comment by daniellerad** [comment]
Actually, item 1 is rebase-related. Item 2 I'm unsure about. Item 3 is enhancement.

**Comment by daniellerad** [comment]
From Jeff about item 2: "Originally lesson plans weren’t listed under the published section—just reporting. After Xaq’s fix a couple weeks back, they started showing up."
