### ISSUE TITLE
create project context

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#99]

**Comment by daniellerad** [comment]
Not sure if this is the right place to put it, but noting that we told them they could add embed code (to a YouTube video, for example) in the body content WYSIWYG area of the Project page.

**Comment by xaqrox** [comment]
@jselt, how would you prefer to accomplish the top area here?
* I could put the image in the sidebar and you could just set padding and stuff carefully, and have the background on the body with the green OR
* rewrite templates and stuff to give you a full width wrapper. definitely more complicated but probably more robust.
![pc-indivproject-final](https://cloud.githubusercontent.com/assets/394919/21942178/edf3dc04-d999-11e6-8735-d722984028dc.jpg)

**Comment by jselt** [comment]
I would say the second, but if it is taking too long than we can do the first option
